apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 894103237817.dkr.ecr.us-east-1.amazonaws.com/jenkinsecr-assignment:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
